version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: korp_postgres
    restart: always
    environment:
      POSTGRES_USER: korp_user
      POSTGRES_PASSWORD: korp_senha
      POSTGRES_DB: korp_estoque
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: